### ISSUE TITLE
Support TiDB

### ISSUE THREAD

**Issue by Avey777** [apecloud/ape-dts#269]
https://github.com/pingcap/tidb

**Comment by qianyiwen2019** [comment]
TiDB as source or destination ?

MySQL -> TiDB  or  Postgres -> TiDB ?

**Comment by Avey777** [comment]
MySQL -> TiDB

**Comment by qianyiwen2019** [comment]
MySQL -> TiDB  is right on the way.

**Comment by qianyiwen2019** [comment]
MySQL -> TiDB is supported now, please have a try.
https://github.com/apecloud/ape-dts/blob/main/docs/en/tutorial/mysql_to_tidb.md
