### ISSUE TITLE
publish pure binary besides docker images for mac/darwin,  linux/arm64,  linux/amd64, windows

### ISSUE THREAD

**Issue by qianyiwen2019** [apecloud/ape-dts#284]

**Comment by suyanhj** [comment]
有考虑添加docker-compose一键部署和web端嘛，多任务管理的情况下手动编辑配置文件比较繁琐吧，图形化中操作应该更便捷一点

**Comment by qianyiwen2019** [comment]
> 有考虑添加docker-compose一键部署和web端嘛，多任务管理的情况下手动编辑配置文件比较繁琐吧，图形化中操作应该更便捷一点

web 端暂时还没有。
docker-compose 我们并不需要，我们只有一个镜像，简单拉起就行。
