### ISSUE TITLE
Can you provide binary package download?

### ISSUE THREAD

**Issue by spihiker** [apecloud/ape-dts#291]
Can you provide binary package download?

**Comment by qianyiwen2019** [comment]
we will do this later

**Comment by qianyiwen2019** [comment]
please find binaries here: https://github.com/apecloud/ape-dts/releases/tag/v2.0.16

**Comment by chutongz** [comment]
Thanks for release the binary file! I met this error when executing on a x86 machine, not sure if it is requiring some other files. Hoping  for reply, thanks!
感谢发布可执行版本！在x64架构芯片上想运行时遇到了以下报错，不确定是否是缺少了必要的文件。期待答复，谢谢！
>./ape-dts --help
thread 'main' panicked at dt-common/src/config/ini_loader.rs:16:14:
failed to open ini file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x5559a74d933a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x5559a7503973 - core::fmt::write::h7550c97b06c86515
   2:     0x5559a74d4583 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x5559a74d9182 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x5559a74da474 - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x5559a74da2ba - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x5559a74daa47 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   7:     0x5559a74da8da - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   8:     0x5559a74d9819 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
   9:     0x5559a74da56c - rust_begin_unwind
  10:     0x5559a58b67a0 - core::panicking::panic_fmt::h0c3082644d1bf418
  11:     0x5559a58b6be6 - core::result::unwrap_failed::hd20b4aa073bda1e2
  12:     0x5559a6b7e8e5 - dt_common::config::ini_loader::IniLoader::new::h5b54cc5cd31d64aa
  13:     0x5559a5b1d735 - dt_precheck::config::task_config::PrecheckTaskConfig::new::h531f2556a1d8a098
  14:     0x5559a59248d3 - dt_main::main::{{closure}}::h4ccb09f71c02816e
  15:     0x5559a593deca - tokio::runtime::park::CachedParkThread::block_on::h56213bdb9edc1898
  16:     0x5559a5a8490c - tokio::runtime::context::runtime::enter_runtime::hb252a01c6c474f3e
  17:     0x5559a5a304d4 - tokio::runtime::runtime::Runtime::block_on::hb6b3fe73a8657f93
  18:     0x5559a59e4148 - dt_main::main::h4fc20ae4e11a4936
  19:     0x5559a59ff583 - std::sys::backtrace::__rust_begin_short_backtrace::h89090b6c258bfd6c
  20:     0x5559a599ff89 - std::rt::lang_start::{{closure}}::haad811cc46fd1b63
  21:     0x5559a74ccdae - std::rt::lang_start_internal::h1c66660c99c8424c
  22:     0x5559a59e4215 - main
  23:     0x7faee7d89a85 - __libc_start_main
                               at /tmp/glibc-2.18/csu/libc-start.c:269
  24:     0x5559a58b7029 - _start
  25:                0x0 - <unknown>
