### ISSUE TITLE
mysql密码含有特殊导致无法连接，如 @ : / ? # 等

### ISSUE THREAD

**Issue by Hironerd** [apecloud/ape-dts#304]
## 描述

- mysql密码含有特殊导致无法连接，如 @ : / ? # 等

## 现象

docker run --rm --network host -v "/tmp/ape_dts/task_config.ini:/task_config.ini" -v "/tmp/ape_dts/check_data_task_log/:/logs/" "$APE_DTS_IMAGE" /task_config.ini 

2024-12-25T03:56:46.445312833+00:00 ERROR default_logger - panic: panicked at dt-main/src/main.rs:19:39:
called `Result::unwrap()` on an `Err` value: error returned from database: 1045 (28000): Access denied for user 'root'@'10.220.136.31' (using password: YES)

Caused by:
    1045 (28000): Access denied for user 'root'@'10.220.136.31' (using password: YES)

## 环境
- OS: CentOS Linux release 7.9.2009 (Core)
- apt-dts version: 2.0.16

**Comment by qianyiwen2019** [comment]
这个已经解决，将含有特殊字符的部分（如密码，用户名）分别单独使用 url 的百分号编码。
如以下用户：
create user user1@'%' identified by 'abc%$#?@';
对应 url 为：
mysql://user1:abc%25%24%23%3F%40@127.0.0.1:3307?ssl-mode=disabled
密码部分：'abc%$#?@'  转义成  'abc%25%24%23%3F%40'

**Comment by Hironerd** [comment]
好的，经测试确实可以了。谢谢。
